### ISSUE TITLE
Integrated + External GPU not supported

### ISSUE THREAD

**Issue by Joly0** [mafiosnik777/enhancr#16]
I am trying to run this on a windows 11 laptop with an external nvidia gpu, though the tool keeps only recognizing the igpu of the laptops cpu, but not the external gpu. I have tried to force it to use the gpu, but it didnt work. Settings only show the igpu and upscaling something results in an error, that my gpu is unsupported (no capable devices found).
This seems to only be an issue with x265, x264 works on my igpu, though i would like to use x265 and my external gpu

**Comment by mafiosnik777** [comment]
Disable Preview & Hardware Encoding, your GPU probably only supports h264 hardware encoding. @Joly0

**Comment by Joly0** [comment]
Hm, more or less this did help. I can see now, that my nvidia gpu is used aswell, but x265 still doesnt work, it shows this error message:
[Pipe] [0 NVIDIA GeForce GTX 1080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1080 Ti]  bugsbn1=0  bugbilz=150  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1080 Ti]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1080 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) Iris(R) Xe Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) Iris(R) Xe Graphics]  bugsbn1=0  bugbilz=192  bugcopc=0  bugihfa=0
[1 Intel(R) Iris(R) Xe Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) Iris(R) Xe Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[Pipe] Starting video output | Threads: 4 | Streams: 2
Script evaluation done in 2.93 seconds
[Pipe] vkAllocateMemory failed -2
[Pipe] vkAllocateMemory failed -2
vkAllocateMemory failed -2
[Pipe] vkAllocateMemory failed -2
vkAllocateMemory failed -2
[Pipe] vkAllocateMemory failed -2
[Pipe] vkWaitForFences failed -4
[Pipe] vkWaitForFences failed -4
[Pipe] vkQueueSubmit failed -4
vkQueueSubmit failed -4
Error: Failed to retrieve frame 1 with error: operator (): inference failed

I tried to tinker around with this, and setting "concurrent streams" to 1 (from 2) i see, it is working now with x265, but very slow (0.4 fps, before changing your suggested settings it was about 8-10 with x264). Not sure if this has something todo with the hardware encoding. But both gpu´s do support 265 encoding, so that should work. But isnt there any option to tell enhancr to "use only one gpu"? It looks to me, like it uses both?

**Comment by Joly0** [comment]
Enabling "Hardware Support" again shows the "no capable devices found" error again, although the gtx 1080ti can encode hevc
![grafik](https://user-images.githubusercontent.com/13993216/235443789-e1cd6d05-9109-4167-846c-ba9e769a5f8b.png)
 https://en.wikipedia.org/wiki/Pascal_%28microarchitecture%29

**Comment by mafiosnik777** [comment]
`[Pipe] vkAllocateMemory failed -2`

You're running out of VRAM here, so yes putting streams to 1 fixes that.

`But isnt there any option to tell enhancr to "use only one gpu"? It looks to me, like it uses both?`

Determining which GPU NCNN uses is quite a gamble, especially with external GPU, or when you change GPUs frequently as GPU IDs change around with that all the time. NCNN just uses one GPU at a time but regardless, even when it just uses your 1080 NCNN always lists all the GPUs in your system.

I'll add something soon so you can change GPU ID manually or some stuff so it figures it out automatically. I think actually no one has managed yet to do that properly in a automated way. Should be possible if you just query c++ ncnn api.

`Enabling "Hardware Support" again shows the "no capable devices found" error again, although the gtx 1080ti can encode hevc`

GTX 1080 Ti can only have up to two concurrent NVENC streams.

See: https://forums.developer.nvidia.com/t/max-of-h264-encode-streams-gtx-1080-ti/56054/2

So now we have this situation on hand:

- Preview is one NVENC Stream
- Checking hardware encoding in settings is one NVENC Stream
- And now if we assume that you have Shadowplay on, that would be another NVENC stream

So that would be 3 simultaneous encoding sessions on your GPU, which it can only do 2 of.

**-> FFmpeg queries nvEncodeAPI and it returns that no capable device is found for the third requested encoding session and it fails.**

My recommendation for you is just turning off hardware encoding for the actual encode and just do encode on CPU, because hardware encoded files are big and it generally just looks really bad. Makes no sense to upscale stuff if you ruin it with Nvenc afterwards anyways. 

Encoding Preview with NVENC on the other hand is fine because its temporally anyways and you just wanna get a rough idea of your output without impacting performance. 

If you do absolutely want to encode on hardware, just use QuickSync from your CPU, the ffmpeg parameters are freely adjustable in enhancr. Just replace `hevc_nvenc` with `hevc_qsv`.

@Joly0

**Comment by mafiosnik777** [comment]
Unfortunately I can't really experiment around much with this, because my A4000 can do like 16 encode sessions simultaneously, but I do believe I told you everything you need to know regarding this matter, so just adjust accordingly.

Closing.

**Comment by Joly0** [comment]
Ahh, i see. Thank you for your input. I highly appreciate it.
