### ISSUE TITLE
 "free" and "pro" versions

### ISSUE THREAD

**Issue by makemota** [mafiosnik777/enhancr#19]
What the difference between "free" and "pro" versions?
How to obtain "pro" versions?

**Comment by mafiosnik777** [comment]
https://patreon.com/mafiosnik @makemota

**Comment by martinlyons** [comment]
Your patreon page doesn't make it abundantly clear that you can go through installing the 'free application' all the way to trying to restore a video and are then confronted that every TensorRT model is 'PRO only'. This is not documentation, it's bait and switch.

I appreciate you have to make a living. But bundling together a bunch of open source models in a UI and then putting the only thing that makes it slightly interesting (tensorRT) behind a paywall isn't much of a product. Sorry.

**Comment by Bubblemint864** [comment]
You are free to use other programs if you don’t want to pay for TensorRT functionality, no one said you have to use this one 🤷‍♀️

**Comment by mafiosnik777** [comment]
@martinlyons 
If a model doesn't have a DirectML/NCNN counterpart it's not some arbitrary limitation, but simply that it's not possible to port that architecture, due to missing operators etc. It's not just throwing a bunch of open source models together, but you actually have to modify the architecture for some, to get them exported.
Even in its free version it's better than any other free GUI + their paid versions, that's just a fact. The alternatives are a joke in terms of speed/usability and/or destroy your drive with extracting frames to it.

Lastly you can check out my friend sudos docker to get the same thing, just for free & without a GUI:
https://github.com/styler00dollar/VSGAN-tensorrt-docker/
