### ISSUE TITLE
Hardware accelerated decoding 

### ISSUE THREAD

**Issue by 78Alpha** [mafiosnik777/enhancr#32]
Was wondering if the option to pass --hwaccel to ffmpeg could be added. For some of the models I tend to run into a CPU bottleneck before CUDA.

**Comment by mafiosnik777** [comment]
Decode barely takes CPU, what you mean is hardware encoding, which is already there.
Wouldn't recommend though, because it looks noticeably worse than encoding on CPU.

Just change the preset in ffmpeg line from slow/medium to fast or something, which will result in a larger file but the bottleneck will be gone. 

`--hwaccel` won't do anything.
