### ISSUE TITLE
missing colorspace parameter

### ISSUE THREAD

**Issue by axw-pub** [mafiosnik777/enhancr#34]
the input video is mp4 hvc1

`[enhancr] Preparing media for restoration process..
[enhancr] Encoding parameters: -c:v h264_nvenc -preset p6 -b_adapt 1 -rc-lookahead 30 -qp 18 -qp_cb_offset -2 -qp_cr_offset -2 -pix_fmt nv12
[enhancr] Mode: Restoration - DPIR (DirectML)
[enhancr] Starting restoration process..

[Pipe] Starting video output | Threads: 8 | Streams: 2
[Pipe] Script evaluation done in 1.62 seconds
[Pipe] Error: Failed to retrieve frame 0 with error: Resize error: Resize error 3074: unrecognized transfer characteristics (0/0/0 => 0/0/0). May need to specify additional colorspace parameters.
Output 8 frames in 0.02 seconds (343.94 fps)
[Pipe] 
[enhancr] Finishing up restoration..
[enhancr] Muxing in streams..
[enhancr] Muxing in streams..
[enhancr] Completed restoring
[enhancr] Completed queue with 0 error(s).`

**Comment by samconrad** [comment]
This error occurs because the input video is missing colorspace and transfer parameters in the input file metadata. Many players will ignore and play the file anyway. You can fix this error by modifying the bitstream filters with ffmpeg which installs with enhancr and is used for encode/decode, default Windows install dir is here -  %LOCALAPPDATA%\enhancr\resources\external\ffmpeg. 

For example if the content is Rec. 709, assuming windows you can try the following in cmd or powershell prompt:
ffmpeg -i INPUT.mkv -codec copy -bsf:v hevc_metadata=colour_primaries=1:transfer_characteristics=1:matrix_coefficients=1 OUTPUT.mkv

Then use the OUTPUT file as your input in enhancr.
I personally have had this issue after I encode videos using AMD's AMF hardware encoder, but not libx264 or libx265 CPU encoders. 

More reading:
https://ffmpeg.org/ffmpeg-bitstream-filters.html#hevc_005fmetadata
